### ISSUE TITLE
handle corrupted download

### ISSUE THREAD

**Issue by eviltik** [udger/udger-updater-nodejs#6]
Try to reproduce this error by downloading a corrupted file

```
        this.versionNext = this.dbNext.prepare("SELECT * FROM udger_db_info").get();
                                       ^
SqliteError: database disk image is malformed
```

Then try to redownload ?

**Comment by eviltik** [comment]
@mallat do you think it's possible to have a new URL to be able to test checksum of the latest release of the db ?

Something like 
```
https://data.udger.com/[MY_KEY]/versionHash
```

Returning something like
```
{
    "sha1":"lksdjflsdjflkdsjflsdfjlsdjflkjsdf",
    "md5":"slkdfjzeopaizepoaziepoaizepoaize"
}
```

The "sha1" attributes indicates a checksum of the sqlite db file containing 160-bit SHA-1 hashes in sha1sum format.

The "md5" attributes indicates a checksum file containing 128-bit MD5 hashes in md5sum format.

https://en.wikipedia.org/wiki/File_verification

**Comment by eviltik** [comment]
Btw, under linux, 2 tools are available to do that: md5sum and sha1sum.

**Comment by mallat** [comment]
Each file has an available checksum. For udgerdb_v3.dat, it is udgerdb_v3_dat.md5 and udgerdb_v3_dat.sha1 (similarly for udgerdb.dat, ie udgerdb_dat.md5 and udgerdb_dat.sha1). The file version is common.
If you would like it to be in json format, it is not a problem to generate it, but you need to choose the name. For example, the name could be db_v3_version.json

**Comment by eviltik** [comment]
huhu !

I didn't know about that, existing file sound's good, let's go with it, thank you !
